/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as GruposIndexRouteImport } from './routes/grupos/index'
import { Route as GruposGrupoIdRouteImport } from './routes/grupos/$grupoId'
import { Route as PesquisadoresIndexRouteImport } from './routes/pesquisadores/index'
import { Route as ProducoesIndexRouteImport } from './routes/producoes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIndexRoute = GruposIndexRouteImport.update({
  id: '/grupos/',
  path: '/grupos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposGrupoIdRoute = GruposGrupoIdRouteImport.update({
  id: '/grupos/$grupoId',
  path: '/grupos/$grupoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisadoresIndexRoute = PesquisadoresIndexRouteImport.update({
  id: '/pesquisadores/',
  path: '/pesquisadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducoesIndexRoute = ProducoesIndexRouteImport.update({
  id: '/producoes/',
  path: '/producoes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/grupos/': typeof GruposIndexRoute
  '/pesquisadores/': typeof PesquisadoresIndexRoute
  '/producoes/': typeof ProducoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/grupos': typeof GruposIndexRoute
  '/pesquisadores': typeof PesquisadoresIndexRoute
  '/producoes': typeof ProducoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/grupos/': typeof GruposIndexRoute
  '/pesquisadores/': typeof PesquisadoresIndexRoute
  '/producoes/': typeof ProducoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/tanstack-query'
    | '/grupos/$grupoId'
    | '/grupos/'
    | '/pesquisadores/'
    | '/producoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/tanstack-query'
    | '/grupos/$grupoId'
    | '/grupos'
    | '/pesquisadores'
    | '/producoes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/tanstack-query'
    | '/grupos/$grupoId'
    | '/grupos/'
    | '/pesquisadores/'
    | '/producoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  GruposGrupoIdRoute: typeof GruposGrupoIdRoute
  GruposIndexRoute: typeof GruposIndexRoute
  PesquisadoresIndexRoute: typeof PesquisadoresIndexRoute
  ProducoesIndexRoute: typeof ProducoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/': {
      id: '/grupos/'
      path: '/grupos'
      fullPath: '/grupos/'
      preLoaderRoute: typeof GruposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/$grupoId': {
      id: '/grupos/$grupoId'
      path: '/grupos/$grupoId'
      fullPath: '/grupos/$grupoId'
      preLoaderRoute: typeof GruposGrupoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisadores/': {
      id: '/pesquisadores/'
      path: '/pesquisadores'
      fullPath: '/pesquisadores/'
      preLoaderRoute: typeof PesquisadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producoes/': {
      id: '/producoes/'
      path: '/producoes'
      fullPath: '/producoes/'
      preLoaderRoute: typeof ProducoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  GruposGrupoIdRoute: GruposGrupoIdRoute,
  GruposIndexRoute: GruposIndexRoute,
  PesquisadoresIndexRoute: PesquisadoresIndexRoute,
  ProducoesIndexRoute: ProducoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
