import type {
  ResearchArticle,
  ResearchGroupSummary,
  ResearchGroupDetail,
  ResearcherProfile,
  DirectoryGroupItem,
  ResearcherItem,
  ProductionItem,
} from '#/core/interfaces'

export const MOCK_DIRECTORY_GROUPS: DirectoryGroupItem[] = [
  {
    id: 'grp-iaa-usp',
    name: 'Laboratório de Inteligência Artificial Aplicada',
    institution: 'USP',
    knowledgeArea: 'Engenharia',
    status: 'Active',
    uf: 'SP',
    since: '2015',
    membersCount: 38,
    leaders: ['Dr. Roberto Ramos', 'Dra. Maria Silva Oliveira'],
    description:
      'Pesquisa avançada em redes neurais profundas, visão computacional e modelos de linguagem aplicados à indústria.',
  },
  {
    id: 'grp-ecol-unesp',
    name: 'Grupo de Estudos em Ecologia de Paisagens',
    institution: 'UNESP',
    knowledgeArea: 'Ciências Biológicas',
    status: 'Active',
    uf: 'SP',
    since: '2018',
    membersCount: 22,
    leaders: ['Dr. Carlos Drummond', 'Dra. Ana Prado'],
    description:
      'Análise espacial de ecossistemas tropicais, dinâmica de desmatamento e conectividade de fragmentos florestais.',
  },
  {
    id: 'grp-redes-ufrj',
    name: 'Núcleo de Pesquisa em Redes Complexas',
    institution: 'UFRJ',
    knowledgeArea: 'Ciências da Computação',
    status: 'Active',
    uf: 'RJ',
    since: '2010',
    membersCount: 45,
    leaders: ['Dr. Carlos Mendes', 'Dr. James Chen'],
    description:
      'Modelagem de topologias de redes em larga escala, teoria dos grafos e dinâmica de informação em mídias digitais.',
  },
  {
    id: 'grp-urban-ufmg',
    name: 'Observatório de Dinâmicas Urbanas',
    institution: 'UFMG',
    knowledgeArea: 'Sociologia',
    status: 'Archived',
    uf: 'MG',
    since: '2005 - 2021',
    membersCount: 16,
    leaders: ['Dra. Lúcia Guimarães'],
    description:
      'Estudo sócio-espacial das transformações metropolitanas e segregação urbana em capitais brasileiras.',
  },
  {
    id: 'grp-bio-unicamp',
    name: 'Centro de Biologia Molecular e Genômica Funcional',
    institution: 'UNICAMP',
    knowledgeArea: 'Ciências Biológicas',
    status: 'Active',
    uf: 'SP',
    since: '2012',
    membersCount: 52,
    leaders: ['Dr. Fernando Toledo', 'Dra. Sarah Jenkins'],
    description:
      'Sequenciamento genômico de alto desempenho e biologia de sistemas para plantas e microrganismos.',
  },
  {
    id: 'grp-quant-ufrgs',
    name: 'Laboratório de Informação e Matéria Quântica',
    institution: 'UFRGS',
    knowledgeArea: 'Física',
    status: 'Active',
    uf: 'RS',
    since: '2016',
    membersCount: 29,
    leaders: ['Dr. Alexandre Chen', 'Dra. Beatriz Luz'],
    description:
      'Controle coerente de estados quânticos, emaranhamento e simulações quânticas em matéria condensada.',
  },
  {
    id: 'grp-saude-ufba',
    name: 'Núcleo de Epidemiologia e Saúde Coletiva',
    institution: 'UFBA',
    knowledgeArea: 'Ciências da Saúde',
    status: 'Active',
    uf: 'BA',
    since: '2014',
    membersCount: 34,
    leaders: ['Dr. Marcos Vinícius', 'Dra. Mariana Rios'],
    description:
      'Vigilância em saúde, determinantes sociais de doenças tropicais negligenciadas e políticas públicas.',
  },
  {
    id: 'grp-energia-ufpe',
    name: 'Grupo de Pesquisa em Energias Renováveis e Hidrogênio Verde',
    institution: 'UFPE',
    knowledgeArea: 'Engenharia',
    status: 'Active',
    uf: 'PE',
    since: '2019',
    membersCount: 27,
    leaders: ['Dr. Paulo Henrique', 'Dra. Clara Silveira'],
    description:
      'Células a combustível, eletrólise de alta eficiência e integração de microrredes eólicas e solares.',
  },
]

export const MOCK_RESEARCHERS: ResearcherItem[] = [
  {
    id: 'res-maria-silva',
    name: 'Dr. Maria Silva Oliveira',
    institution: 'Universidade de São Paulo (USP)',
    uf: 'SP',
    degree: 'Doutorado em Ciência da Computação',
    yearIndexed: '2018',
    isPQFellow: true,
    bolsaProdutividade: 'PQ-1A',
    isActive: true,
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDAP-bzR_2RU2gw1j2raRyIOTEbnAXn6h4Rw3hY8pJgDQbzmQfQVTV1gAKcTGUJNgaS5oIifjoznpJQACcnMHRElNJ7Grk3hIHugGmE-V_Ws2lZtc1Q9Du2hoF0vYo_NAu1lQykjbREARVBD29d-ZWV4W6Lxt8o5Py8Ome6uhlsqpcl_LC5JFBdaEohPPukROSYARP8L45lPKyUvlYXkeyHrHZt8QjZxPJDwUnzPdaPhBmLdniL3VpR',
    citationsCount: 4320,
    hIndex: 32,
    productionsCount: 88,
    lattesId: '5492109483920194',
    field: 'Ciência da Computação',
    bio: 'Professora Titular no Departamento de Ciência da Computação (USP) com ênfase em Aprendizado Profundo e Sistemas Autônomos.',
    groups: ['Laboratório de Inteligência Artificial Aplicada'],
  },
  {
    id: 'res-joao-costa',
    name: 'João Costa Pereira',
    institution: 'UNICAMP',
    uf: 'SP',
    degree: 'Mestrado em Engenharia Elétrica',
    yearIndexed: '2020',
    isPQFellow: false,
    isActive: true,
    initials: 'JC',
    citationsCount: 890,
    hIndex: 14,
    productionsCount: 26,
    lattesId: '1092837465920193',
    field: 'Engenharia',
    bio: 'Pesquisador em processamento de sinais, redes elétricas inteligentes e microrredes de distribuição.',
    groups: ['Núcleo de Pesquisa em Redes Complexas'],
  },
  {
    id: 'res-carlos-mendes',
    name: 'Dr. Carlos Mendes',
    institution: 'UFRJ',
    uf: 'RJ',
    degree: 'Doutorado em Física',
    yearIndexed: '2015',
    isPQFellow: false,
    isActive: false,
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAHL3SKRkBQXqzJZf_6OrdxOs0UCPS-kS-AlOQonM5w8CeFDqhk21j-mEcGq7jQozQC3LqzbfnjHMh6SAwamOs9SWgsVWSdEoAXze5s5jf9pifDuBNcUvzdlSoJeTsxlJPaz94UdQoLHIWSdJZU6c-HPWFWHL_nilrclBcSby0ILG-F5AzuGZNg0t-QFunhVCXRbe5EL-0Fd82qkDH9ZCtBH8Xq95UnzSbv7AlXzpYWCfEkYYnn1ckY',
    citationsCount: 2840,
    hIndex: 25,
    productionsCount: 54,
    lattesId: '8839201948271039',
    field: 'Física',
    bio: 'Pesquisa em física da matéria condensada teórica e transições de fase quânticas em materiais bidimensionais.',
    groups: ['Laboratório de Matéria Quântica e Nanotecnologia'],
  },
  {
    id: 'res-elena-rostova',
    name: 'Dr. Elena Rostova',
    institution: 'Universidade de São Paulo (USP)',
    uf: 'SP',
    degree: 'Doutorado em Linguística Computacional',
    yearIndexed: '2014',
    isPQFellow: true,
    bolsaProdutividade: 'PQ-1B',
    isActive: true,
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB68LF8ioTigmnBpzASI-EXJ7TAw7CzhmDjvT-M9cQIe7M4wgE55AlT-QTN8DVyyk0fD8PZOmDKUiE4etvoFu-hgemc52e20MXlvSKN7oARbxAKS3MwyJuDtIvw1GNGFFtTng7G_cDhnXV1nQv5UF81daM-LgYLa-UQxima0x0ZgocLbPEY0iieJcqJbBoyMI-5dm3BgnsMkfEgPPfkSSfanDdZaK0RBj9gcVGMvxm8fGajOmieKp7n',
    citationsCount: 12400,
    hIndex: 42,
    productionsCount: 156,
    lattesId: '9840291840291840',
    field: 'Ciência da Computação',
    bio: 'Líder de pesquisa em Processamento de Linguagem Natural, modelos de fundação multilíngues e representação semântica.',
    groups: ['Laboratório de Inteligência Artificial Aplicada'],
  },
  {
    id: 'res-ana-prado',
    name: 'Dra. Ana Prado',
    institution: 'UNESP',
    uf: 'SP',
    degree: 'Doutorado em Ecologia',
    yearIndexed: '2019',
    isPQFellow: true,
    bolsaProdutividade: 'PQ-2',
    isActive: true,
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCTByR863c-ADuvSMo4teqCnL1UkHT0_MEdoEdQUkIYKv8TGUYkkVl3zS9LrWdn6wa6CPLbWEWg6k97YEo79CEN-8topeFBiqZcow433A8GUr1og6TX0EOrG5yyyLRlK26xt_b1NjXR8IC3L3QF5cy-FnhQRIo7BgQzWq5sy5S2FvoOwKrLmx44Y_sWiyD5GoJLHWBZ2-FQ4-h5fRzEj5onL06VoG1tMA5W1ATznK8DNkfvlMabIen6',
    citationsCount: 3120,
    hIndex: 28,
    productionsCount: 62,
    lattesId: '2039482910394829',
    field: 'Ciências Biológicas',
    bio: 'Bióloga e ecóloga com foco em conservação de ecossistemas florestais e restauração biológica.',
    groups: ['Grupo de Estudos em Ecologia de Paisagens'],
  },
  {
    id: 'res-fernando-toledo',
    name: 'Dr. Fernando Toledo',
    institution: 'UNICAMP',
    uf: 'SP',
    degree: 'Doutorado em Genética e Biologia Molecular',
    yearIndexed: '2016',
    isPQFellow: false,
    isActive: true,
    initials: 'FT',
    citationsCount: 1980,
    hIndex: 21,
    productionsCount: 41,
    lattesId: '7749201938491029',
    field: 'Ciências Biológicas',
    bio: 'Especialista em bioinformática, genômica funcional e edição gênica aplicada a culturas agrícolas tropicais.',
    groups: ['Núcleo de Pesquisa em Polímeros Sustentáveis'],
  },
  {
    id: 'res-lucas-guimaraes',
    name: 'Lucas Guimarães Ramos',
    institution: 'UFMG',
    uf: 'MG',
    degree: 'Especialização em Análise de Dados Urbanos',
    yearIndexed: '2021',
    isPQFellow: false,
    isActive: true,
    initials: 'LG',
    citationsCount: 420,
    hIndex: 9,
    productionsCount: 15,
    lattesId: '3948201938402918',
    field: 'Ciências Sociais Aplicadas',
    bio: 'Pesquisador em dinâmicas metropolitanas, mobilidade urbana ativa e geoprocessamento aplicado a políticas públicas.',
    groups: ['Observatório de Dinâmicas Urbanas'],
  },
  {
    id: 'res-mariana-rios',
    name: 'Dra. Mariana Rios',
    institution: 'UFBA',
    uf: 'BA',
    degree: 'Doutorado em Saúde Pública',
    yearIndexed: '2017',
    isPQFellow: true,
    bolsaProdutividade: 'PQ-2',
    isActive: true,
    initials: 'MR',
    citationsCount: 2450,
    hIndex: 24,
    productionsCount: 52,
    lattesId: '8201938402918402',
    field: 'Ciências da Saúde',
    bio: 'Epidemiologista dedicada a modelos preditivos de contágio de arboviroses e atenção primária em saúde coletiva.',
    groups: ['Núcleo de Epidemiologia e Saúde Coletiva'],
  },
  {
    id: 'res-paulo-henrique',
    name: 'Dr. Paulo Henrique',
    institution: 'UFPE',
    uf: 'PE',
    degree: 'Doutorado em Engenharia Química',
    yearIndexed: '2018',
    isPQFellow: true,
    bolsaProdutividade: 'PQ-1D',
    isActive: true,
    initials: 'PH',
    citationsCount: 3890,
    hIndex: 30,
    productionsCount: 74,
    lattesId: '9182039485720192',
    field: 'Engenharia',
    bio: 'Especialista em transição energética, rotas termoquímicas para hidrogênio verde e catálise heterogênea.',
    groups: ['Grupo de Pesquisa em Energias Renováveis e Hidrogênio Verde'],
  },
]

export const MOCK_PRODUCTIONS: ProductionItem[] = [
  {
    id: 'prod-1',
    title:
      'Machine learning approaches for predictive maintenance in industrial manufacturing systems',
    authors: 'Silva, J. M., Santos, R. A., & Oliveira, C. L.',
    venue: 'Journal of Manufacturing Systems, v. 45, p. 112-128.',
    journalOrConference: 'Journal of Manufacturing Systems, v. 45, p. 112-128.',
    year: '2023',
    qualis: 'A1',
    type: 'Artigo',
    openAccess: true,
    isOpenAccess: true,
    citations: 84,
    doi: '10.1016/j.jmsy.2023.04.012',
    institution: 'Universidade de São Paulo (USP)',
    groupName: 'Laboratório de Inteligência Artificial Aplicada',
    abstract:
      'We present state-of-the-art predictive maintenance paradigms evaluating multimodal sensor streams using self-supervised Transformer models, achieving high accuracy in industrial settings.',
  },
  {
    id: 'prod-2',
    title:
      'Impactos das mudanças climáticas na biodiversidade da Amazônia: uma revisão sistemática',
    authors: 'Costa, M. F., Ferreira, L. B., & Almeida, P.',
    venue:
      'In: Biodiversidade e Conservação no Século XXI (pp. 45-67). Editora Universitária.',
    journalOrConference:
      'In: Biodiversidade e Conservação no Século XXI (pp. 45-67). Editora Universitária.',
    year: '2022',
    qualis: 'A2',
    type: 'Capítulo',
    openAccess: false,
    isOpenAccess: false,
    citations: 46,
    doi: '10.1007/978-3-030-92819-4_4',
    institution: 'Universidade Estadual Paulista (UNESP)',
    groupName: 'Grupo de Estudos em Ecologia de Paisagens',
    abstract:
      'Revisão integrativa sobre projeções climáticas e seus impactos na distribuição de espécies de flora e fauna na bacia amazônica ao longo do século XXI.',
  },
  {
    id: 'prod-3',
    title:
      'Desenvolvimento de biopolímeros a partir de resíduos agroindustriais para embalagens sustentáveis',
    authors: 'Pereira, A. C., Gomes, T. R., & Rocha, E. M.',
    venue: 'Polímeros: Ciência e Tecnologia, v. 32, e2023015.',
    journalOrConference: 'Polímeros: Ciência e Tecnologia, v. 32, e2023015.',
    year: '2023',
    qualis: 'A2',
    type: 'Artigo',
    openAccess: true,
    isOpenAccess: true,
    citations: 62,
    doi: '10.1590/0104-1428.20230015',
    institution: 'Universidade Federal do Rio de Janeiro (UFRJ)',
    groupName: 'Núcleo de Pesquisa em Polímeros Sustentáveis',
    abstract:
      'Investigação da síntese e caracterização térmica de filmes biodegradáveis formulados a partir do bagaço de cana-de-açúcar e fécula de mandioca.',
  },
  {
    id: 'prod-4',
    title:
      'Topological Qubits at Room Temperature: High-Coherence Graphene Architectures',
    authors: 'Chen, A., Vance, E., & Rostova, E.',
    venue: 'Physical Review Letters, 131(12), 120401.',
    journalOrConference: 'Physical Review Letters, 131(12), 120401.',
    year: '2024',
    qualis: 'A1',
    type: 'Artigo',
    openAccess: true,
    isOpenAccess: true,
    citations: 112,
    doi: '10.1103/PhysRevLett.131.120401',
    institution: 'Universidade de São Paulo (USP)',
    groupName: 'Laboratório de Matéria Quântica e Nanotecnologia',
    abstract:
      'Experimental demonstration of topological braiding phases maintained at ambient conditions using synthetic superlattice heterostructures.',
  },
  {
    id: 'prod-5',
    title:
      'Fundamentos de Redes Complexas e Grafos Aleatórios Aplicados à Ciência de Dados',
    authors: 'Mendes, C., & Santos, F. L.',
    venue: 'Editora Acadêmica Nacional, 340 páginas.',
    journalOrConference: 'Editora Acadêmica Nacional, 340 páginas.',
    year: '2021',
    qualis: 'A3',
    type: 'Livro',
    openAccess: false,
    isOpenAccess: false,
    citations: 175,
    doi: '10.1000/isbn.978-85-7000-001-2',
    institution: 'Universidade Estadual de Campinas (UNICAMP)',
    groupName: 'Núcleo de Pesquisa em Redes Complexas',
    abstract:
      'Livro-texto abrangente cobrindo propriedades de pequenos mundos, conectividade scale-free, algoritmos de detecção de comunidades e dinâmica de percolação.',
  },
  {
    id: 'prod-6',
    title:
      'Low-Latency Quantization of Large Language Models for Edge Inference',
    authors: 'Rostova, E., Jenkins, S., & Chen, J.',
    venue:
      'Proceedings of the 61st Annual Meeting of the Association for Computational Linguistics (ACL), pp. 240-255.',
    journalOrConference: 'Proceedings of the 61st ACL, pp. 240-255.',
    year: '2023',
    qualis: 'A1',
    type: 'Trabalhos em Eventos',
    openAccess: true,
    isOpenAccess: true,
    citations: 218,
    doi: '10.18653/v1/2023.acl-long.15',
    institution: 'Universidade de São Paulo (USP)',
    groupName: 'Laboratório de Inteligência Artificial Aplicada',
    abstract:
      'Sub-4-bit uniform integer quantization methods for transformer attention layers allowing real-time text generation on embedded microprocessors.',
  },
  {
    id: 'prod-7',
    title:
      'Vigilância Epidemiológica de Arboviroses Urbanas e Modelagem Espaço-Temporal no Nordeste',
    authors: 'Rios, M., Vinícius, M., & Silveira, C.',
    venue: 'Revista de Saúde Pública, v. 57, n. 14, pp. 1-12.',
    journalOrConference: 'Revista de Saúde Pública, v. 57, n. 14, pp. 1-12.',
    year: '2022',
    qualis: 'A2',
    type: 'Artigo',
    openAccess: true,
    isOpenAccess: true,
    citations: 79,
    doi: '10.11606/s1518-8787.2022057004412',
    institution: 'Universidade Federal da Bahia (UFBA)',
    groupName: 'Núcleo de Epidemiologia e Saúde Coletiva',
    abstract:
      'Análise espaço-temporal da incidência de dengue, zika e chikungunya utilizando modelos bayesianos hierárquicos e dados climáticos de alta resolução.',
  },
  {
    id: 'prod-8',
    title:
      'Produção de Hidrogênio Verde via Eletrólise Solar de Alta Eficiência no Semiárido Brasileiro',
    authors: 'Henrique, P., Toledo, F., & Prado, A.',
    venue:
      'International Journal of Hydrogen Energy, v. 48, n. 32, pp. 11980-11995.',
    journalOrConference:
      'Int. Journal of Hydrogen Energy, v. 48, pp. 11980-11995.',
    year: '2024',
    qualis: 'A1',
    type: 'Artigo',
    openAccess: true,
    isOpenAccess: true,
    citations: 135,
    doi: '10.1016/j.ijhydene.2023.11.082',
    institution: 'Universidade Federal de Pernambuco (UFPE)',
    groupName: 'Grupo de Pesquisa em Energias Renováveis',
    abstract:
      'Avaliação técnica e econômica do acoplamento direto de usinas solares fotovoltaicas com eletrolisadores de membrana de troca de prótons (PEM).',
  },
  {
    id: 'prod-9',
    title:
      'Segregação Socioespacial e Acesso a Infraestruturas Urbanas nas Metrópoles Brasileiras',
    authors: 'Guimarães, L., & Ramos, R.',
    venue: 'Cadernos Metrópole, v. 23, n. 51, pp. 415-438.',
    journalOrConference: 'Cadernos Metrópole, v. 23, n. 51, pp. 415-438.',
    year: '2021',
    qualis: 'A4',
    type: 'Artigo',
    openAccess: true,
    isOpenAccess: true,
    citations: 53,
    doi: '10.1590/2236-9996.2021-5116',
    institution: 'Universidade Federal de Minas Gerais (UFMG)',
    groupName: 'Observatório de Dinâmicas Urbanas',
    abstract:
      'Estudo empírico sobre as desigualdades no acesso ao transporte público e saneamento básico nas regiões metropolitanas de Belo Horizonte e São Paulo.',
  },
  {
    id: 'prod-10',
    title:
      'Emaranhamento Quântico em Sistemas de Muitos Corpos: Dinâmica Fora do Equilíbrio',
    authors: 'Chen, A., & Luz, B.',
    venue: 'Physical Review B, v. 106, n. 8, 085110.',
    journalOrConference: 'Physical Review B, v. 106, n. 8, 085110.',
    year: '2022',
    qualis: 'B1',
    type: 'Artigo',
    openAccess: false,
    isOpenAccess: false,
    citations: 38,
    doi: '10.1103/PhysRevB.106.085110',
    institution: 'Universidade Federal do Rio Grande do Sul (UFRGS)',
    groupName: 'Laboratório de Informação e Matéria Quântica',
    abstract:
      'Cálculo analítico e numérico do crescimento da entropia de emaranhamento após quenches quânticos globais em cadeias de spin unidimensionais.',
  },
]

export const MOCK_ARTICLES: ResearchArticle[] = [
  {
    id: 'art-1',
    title: 'Algorithmic Bias in Predictive Policing Models',
    abstract:
      'A comprehensive review of algorithmic fairness in predictive policing, analyzing datasets from major metropolitan areas to identify systemic biases and propose mitigation strategies.',
    tags: ['AI Ethics', 'Peer Reviewed'],
    author: {
      id: 'author-e-vance',
      name: 'Dr. E. Vance',
      role: 'Associate Professor',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCqdZWXLizGJ7j01uVQH5eJoklhisTp4ZNR6vy_oQX6G7vFN9wAsZ9_cTh6wQUo5sK6MszCxDK1Q3N1Q4q1xHqdWoW1F4O3i0cCUXHTdFAwuYN60wNw8PBvWHIA6q0dup9N1DxYcUKVN4bhfntto2rBhUc4KyP4hv51w2yCB0pWLjwhd4snfhQYq-XMu6wUW-B1am2n1aVmOOXWo21DIvVWmKnYKk7ljXdxo54vS-7utKozgHgX9vdj',
      institution: 'Stanford University',
    },
    citations: 142,
    field: 'Computer Science',
    publicationDate: '2024-01-15',
    journal: 'Journal of Artificial Intelligence Ethics, Vol. 8',
    doi: '10.1016/j.aie.2024.01.004',
  },
  {
    id: 'art-2',
    title: 'Topological Qubits at Room Temperature',
    abstract:
      'We present experimental evidence of topological stabilization of qubits operating near room temperature using a novel graphene-based lattice structure.',
    tags: ['Quantum Computing', 'Open Access'],
    author: {
      id: 'author-chen-et-al',
      name: 'A. Chen et al.',
      role: 'Principal Researcher',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuD5aD6SOQZyNjCAEoRHlUQJTZgJsxaUNrzBJ3iuhYmzKyEozN0o27js-MQp_pCY4JXER1GT3NdZexVs7isXI6zOSC5Apmahhs0zja4C1V-DBAN576-MaHUpaucznBowurCvatygJmq-9b2koqikZrZvIbQwXLcXHPZwDD46QZ4hA-JVKALnK1feggoxZDQfdC1eR-rO-psFEFocWoG9iUSQNG4Wjf2kfatDpAZ_P8Wlid0yv8EHZCAO',
      institution: 'Max Planck Institute',
    },
    citations: 89,
    field: 'Physics',
    publicationDate: '2023-11-20',
    journal: 'Nature Quantum Information, 34(4)',
    doi: '10.1038/s41534-023-00789-2',
  },
  {
    id: 'art-3',
    title: 'Synthetic Biology Circuits for Targeted Oncology Delivery',
    abstract:
      'Engineered cellular logic gates implemented within synthetic bacterial strains demonstrate high selectivity in tumor microenvironment sensing and payload release.',
    tags: ['Synthetic Biology', 'Preprint'],
    author: {
      id: 'author-sarah-jenkins',
      name: 'Dr. Sarah Jenkins',
      role: 'Postdoctoral Fellow',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCTByR863c-ADuvSMo4teqCnL1UkHT0_MEdoEdQUkIYKv8TGUYkkVl3zS9LrWdn6wa6CPLbWEWg6k97YEo79CEN-8topeFBiqZcow433A8GUr1og6TX0EOrG5yyyLRlK26xt_b1NjXR8IC3L3QF5cy-FnhQRIo7BgQzWq5sy5S2FvoOwKrLmx44Y_sWiyD5GoJLHWBZ2-FQ4-h5fRzEj5onL06VoG1tMA5W1ATznK8DNkfvlMabIen6',
      institution: 'MIT Synthetic Biology Center',
    },
    citations: 64,
    field: 'Biology',
    publicationDate: '2023-09-12',
    journal: 'Cellular & Molecular Bioengineering',
    doi: '10.1007/s12195-023-00774-1',
  },
  {
    id: 'art-4',
    title: 'High-Resolution Neural Decoding via Low-Power Edge Accelerators',
    abstract:
      'A quantized Transformer architecture implemented on custom ASICs achieving real-time invasive motor cortex decoding with sub-5ms latency and milliwatt power consumption.',
    tags: ['Neuroengineering', 'Peer Reviewed'],
    author: {
      id: 'author-elena-rostova',
      name: 'Dr. Elena Rostova',
      role: 'Professor of Computational Linguistics',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuB68LF8ioTigmnBpzASI-EXJ7TAw7CzhmDjvT-M9cQIe7M4wgE55AlT-QTN8DVyyk0fD8PZOmDKUiE4etvoFu-hgemc52e20MXlvSKN7oARbxAKS3MwyJuDtIvw1GNGFFtTng7G_cDhnXV1nQv5UF81daM-LgYLa-UQxima0x0ZgocLbPEY0iieJcqJbBoyMI-5dm3BgnsMkfEgPPfkSSfanDdZaK0RBj9gcVGMvxm8fGajOmieKp7n',
      institution: 'Massachusetts Institute of Technology',
    },
    citations: 215,
    field: 'Medicine',
    publicationDate: '2024-02-01',
    journal: 'IEEE Transactions on Biomedical Circuits and Systems',
    doi: '10.1109/TBCAS.2024.3359012',
  },
]

export const MOCK_RESEARCH_GROUPS: ResearchGroupSummary[] = [
  {
    id: 'grp-iaa-usp',
    name: 'Laboratório de Inteligência Artificial Aplicada',
    description:
      'Pesquisa avançada em redes neurais profundas, visão computacional e modelos de linguagem.',
    membersCount: 38,
    icon: 'cpu',
  },
  {
    id: 'grp-ecol-unesp',
    name: 'Grupo de Estudos em Ecologia de Paisagens',
    description:
      'Análise espacial de ecossistemas tropicais e dinâmica de desmatamento.',
    membersCount: 22,
    icon: 'public',
  },
  {
    id: 'grp-redes-ufrj',
    name: 'Núcleo de Pesquisa em Redes Complexas',
    description:
      'Modelagem de topologias de redes em larga escala e teoria dos grafos.',
    membersCount: 45,
    icon: 'hub',
  },
]

export const MOCK_GROUP_DETAIL: ResearchGroupDetail = {
  id: 'DGP-44521',
  name: 'Laboratório de Inteligência Artificial Aplicada',
  primaryArea: 'Inteligência Artificial & Computação',
  secondaryTag: 'Grupo de Pesquisa Certificado DGP/CNPq',
  description:
    'Desenvolvendo arquiteturas neurais escaláveis para linguagens de baixos recursos e computação em borda. O laboratório reúne pesquisadores multidisciplinares dedicados ao avanço ético e eficiente da IA.',
  stats: {
    members: 38,
    publications: 184,
    projects: 14,
    formationYear: 2015,
    location: 'São Paulo, SP',
  },
  coverImage:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuB-hih7Y5m3lR7ii9XZ7ORR3nmbpfenb7637uRlUXHFMvMp1DiysgMQwfKuuTLvphNOAocLubArhhnjbZWUqugqV04GYkfne-NlVqoM9Siw6Wb4d8MVR74aN9L2rNafs9iuWLZCcb1P-u-I0a-I7uZPWVsuUsb4bJx9y4OBpi-RNhKu1heYexXIfcMXS7p80ejiTq76xVUuLDowAg9Ijk_mSLlPORehK_kBZM-4vXs8UPugvCrxcaRf',
  institutionalAffiliation: {
    hostInstitution: {
      name: 'Universidade de São Paulo',
      code: 'USP',
    },
    partnerInstitutions: [
      { name: 'FAPESP', code: 'FAPESP' },
      { name: 'CNPq', code: 'CNPq' },
      { name: 'CGI.br', code: 'CGI.br' },
      { name: 'CAPES', code: 'CAPES' },
    ],
  },
  contactInfo: {
    website: 'https://oda-platform.org/groups/iaa-usp',
    email: 'contato@iaa.usp.br',
    socialHandle: '@iaa_usp_research',
  },
  researchLines: [
    {
      title: 'Otimização e Compressão de LLMs',
      isMainFocus: true,
      area: 'Inteligência Artificial',
      description:
        'Investigando novas técnicas de poda estruturada, quantização 4-bit e destilação de conhecimento para implantar modelos de linguagem em hardware restrito.',
      keywords: ['Quantização', 'Poda', 'Destilação', 'Eficiência'],
      applicationSectors: [
        'Saúde Digital',
        'Automação Industrial',
        'Processamento de Linguagem Natural',
      ],
    },
    {
      title: 'Modelos Fundacionais para Bioinformática',
      isMainFocus: false,
      area: 'Ciência da Computação & Bioinformática',
      description:
        'Modelos de difusão geométrica aplicados ao enovelamento tridimensional de proteínas e triagem virtual de candidatos a fármacos.',
      keywords: [
        'Difusão Geométrica',
        'Enovelamento',
        'Docking',
        'Transformers',
      ],
      applicationSectors: [
        'Desenvolvimento Farmacêutico',
        'Biotecnologia Médica',
      ],
    },
  ],
  leaders: [
    {
      id: 'res-maria-silva',
      name: 'Dra. Maria Silva Oliveira',
      role: 'Líder do Grupo / Investigadora Principal',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDAP-bzR_2RU2gw1j2raRyIOTEbnAXn6h4Rw3hY8pJgDQbzmQfQVTV1gAKcTGUJNgaS5oIifjoznpJQACcnMHRElNJ7Grk3hIHugGmE-V_Ws2lZtc1Q9Du2hoF0vYo_NAu1lQykjbREARVBD29d-ZWV4W6Lxt8o5Py8Ome6uhlsqpcl_LC5JFBdaEohPPukROSYARP8L45lPKyUvlYXkeyHrHZt8QjZxPJDwUnzPdaPhBmLdniL3VpR',
      institution: 'USP',
    },
  ],
  members: [
    {
      id: 'res-maria-silva',
      name: 'Dra. Maria Silva Oliveira',
      role: 'Principal Investigator',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDAP-bzR_2RU2gw1j2raRyIOTEbnAXn6h4Rw3hY8pJgDQbzmQfQVTV1gAKcTGUJNgaS5oIifjoznpJQACcnMHRElNJ7Grk3hIHugGmE-V_Ws2lZtc1Q9Du2hoF0vYo_NAu1lQykjbREARVBD29d-ZWV4W6Lxt8o5Py8Ome6uhlsqpcl_LC5JFBdaEohPPukROSYARP8L45lPKyUvlYXkeyHrHZt8QjZxPJDwUnzPdaPhBmLdniL3VpR',
    },
    {
      id: 'author-james-chen',
      name: 'James Chen, Ph.D.',
      role: 'Senior Researcher',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDJUBWwPjnNLomIG6njYbqkjl-Txrctart6PloNRzk9HzAT8F2Yb4d4kWK435R69FRrrBY93inUDNcBj0WfEkDkzi0byU98zFNbBmHx-sTA1m1Fos66ZjQcXhsbr0-mTGN7Abf5guufGUx-xzD1Jvwpgp6CyaplpI4F_jUHL7S7p4R_jfTqmYvze7t7V3gtwlfs7HdunsFeq8Sv6WkMtcTV5GC-srUNmN8cGP4pXhu-qOLYCgv_tonb',
    },
    {
      id: 'author-sarah-jenkins',
      name: 'Sarah Jenkins',
      role: 'Postdoctoral Fellow',
      avatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCTByR863c-ADuvSMo4teqCnL1UkHT0_MEdoEdQUkIYKv8TGUYkkVl3zS9LrWdn6wa6CPLbWEWg6k97YEo79CEN-8topeFBiqZcow433A8GUr1og6TX0EOrG5yyyLRlK26xt_b1NjXR8IC3L3QF5cy-FnhQRIo7BgQzWq5sy5S2FvoOwKrLmx44Y_sWiyD5GoJLHWBZ2-FQ4-h5fRzEj5onL06VoG1tMA5W1ATznK8DNkfvlMabIen6',
    },
  ],
}

export const MOCK_RESEARCHER_PROFILE: ResearcherProfile = {
  id: 'res-maria-silva',
  name: 'Dr. Maria Silva Oliveira',
  role: 'Professora Titular em Ciência da Computação',
  institution: 'Universidade de São Paulo (USP)',
  avatar:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDAP-bzR_2RU2gw1j2raRyIOTEbnAXn6h4Rw3hY8pJgDQbzmQfQVTV1gAKcTGUJNgaS5oIifjoznpJQACcnMHRElNJ7Grk3hIHugGmE-V_Ws2lZtc1Q9Du2hoF0vYo_NAu1lQykjbREARVBD29d-ZWV4W6Lxt8o5Py8Ome6uhlsqpcl_LC5JFBdaEohPPukROSYARP8L45lPKyUvlYXkeyHrHZt8QjZxPJDwUnzPdaPhBmLdniL3VpR',
  stats: {
    hIndex: 32,
    citations: '4.3k',
    publications: 114,
    yearsActive: 15,
  },
  interests: [
    'Inteligência Artificial',
    'Machine Learning',
    'Visão Computacional',
    'Deep Learning',
    'Processamento de Linguagem Natural',
  ],
  affiliatedGroups: [
    {
      id: 'grp-iaa-usp',
      name: 'Laboratório de Inteligência Artificial Aplicada',
      role: 'Líder do Grupo',
      iconType: 'ai',
    },
    {
      id: 'grp-redes-ufrj',
      name: 'Núcleo de Pesquisa em Redes Complexas',
      role: 'Pesquisadora Associada',
      iconType: 'cognitive',
    },
  ],
  selectedPublications: [
    {
      id: 'prod-1',
      title:
        'Machine learning approaches for predictive maintenance in industrial manufacturing systems',
      authors: 'Silva, J. M., Santos, R. A., & Oliveira, C. L.',
      journal: 'Journal of Manufacturing Systems, v. 45, p. 112-128.',
      year: 2023,
      citations: 84,
      pdfAvailable: true,
    },
    {
      id: 'prod-6',
      title:
        'Low-Latency Quantization of Large Language Models for Edge Inference',
      authors: 'Rostova, E., Jenkins, S., & Chen, J.',
      journal: 'Proceedings of the 61st ACL, pp. 240-255.',
      year: 2023,
      citations: 218,
      pdfAvailable: true,
    },
  ],
}
